# EDA for the latest version of Strucke Data

In this notebook the aim is to see the unique values of every row, see if there is anything to be manually resolver or mapped, and understand how much of the data needs cleaning. first a bit of brute force to see all the unique values for every column.

In [1]:
import pandas as pd

df = pd.read_csv("../data/StruckeC14_Sweden_v1.csv")
print(df.shape)
df.head()

(30301, 37)

,socken,landskap,place_name,raa_id,site_type,site_id,uppdragsnummer,lab_id,c14_age_bp,c14_error,...,cal_95_min,cal_95_max,median_cal_year,calibration_method,calibration_status,author,publication_year,title,journal,place_of_publication
0,Jörlanda,Bohuslän,Kyrkeby 3:34 m.fl.,Jörlanda 158,Boplats,L1969:5267,000103367,Ua-49252,2841.0,33.0,...,-913.0,-1110.0,-997.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Åberg, Joakim",2015.0,Bergsmonument och boplatser i Jörlanda,"Bohusläns museum Rapport, 2015:14",Uddevalla
1,Jörlanda,Bohuslän,Berg1:69,Jörlanda 185,Boplats,L1970:9431,NaN,T-8772,1720.0,80.0,...,541.0,132.0,339.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Johansson, Nils",1995.0,Tre boplatser i Spekerödsdalen,"UV Väst, Rapport 1995:1",Kungsbacka
2,Jörlanda,Bohuslän,Berg1:69,Jörlanda 185,Boplats,L1970:9431,NaN,T-8773,2890.0,105.0,...,-830.0,-1381.0,-1086.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Johansson, Nils",1995.0,Tre boplatser i Spekerödsdalen,"UV Väst, Rapport 1995:1",Kungsbacka
3,Jörlanda,Bohuslän,Berg1:69,Jörlanda 185,Boplats,L1970:9431,NaN,T-8774,2015.0,75.0,...,207.0,-333.0,-5.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Johansson, Nils",1995.0,Tre boplatser i Spekerödsdalen,"UV Väst, Rapport 1995:1",Kungsbacka
4,Jörlanda,Bohuslän,Berg1:69,Jörlanda 185,Boplats,L1970:9431,NaN,T-8775,1990.0,55.0,...,203.0,-144.0,29.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Johansson, Nils",1995.0,Tre boplatser i Spekerödsdalen,"UV Väst, Rapport 1995:1",Kungsbacka

In [2]:
col = "socken"
vc = df[col].value_counts(dropna=False).reset_index().sort_values(by=col)
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

socken: 1055 unique values

         socken  count
216       Abild     35
152      Adelsö     53
959   Agunnaryd      1
372         Ala     15
831      Alböke      2
..          ...    ...
284   Överkalix     25
483   Överluleå     10
674    Överselö      5
799  Övertorneå      3
226      Övraby     33

[1055 rows x 2 columns]

In [3]:
col = "landskap"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

landskap: 36 unique values

         landskap  count
0         Uppland   6042
1           Skåne   4780
2    Östergötland   3212
3    Södermanland   2942
4         Halland   1835
5        Bohuslän   1773
6         Småland   1760
7           Närke   1321
8   Västergötland   1262
9     Västmanland   1247
10        Dalarna    669
11       Blekinge    563
12       Värmland    379
13     Norrbotten    328
14        Gotland    294
15       Lappland    293
16       Medelpad    269
17          Öland    236
18       Jämtland    214
19             Bo    173
20   Ångermanland    116
21     Härjedalen    108
22    Hälsingland     88
23    Gästrikland     83
24             Vg     81
25             Ha     79
26   Västerbotten     42
27             Sm     39
28             Sk     18
29       Dalsland     16
30             Sö     15
31             Nä     11
32             vg      5
33             Vs      3
34             Up      3
35             Ög      2

In [4]:
col = "place_name"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

place_name: 5001 unique values

               place_name  count
0        Lockarp 2:1 m fl    223
1          Spallationen 1    144
2             Rödbobacken    134
3              Akalla 4:1    118
4     Gamla Uppsala 21:52    115
...                   ...    ...
4996              Åby 2:1      1
4997            Valla 5:1      1
4998        Hunnebo 1:647      1
4999       Lyttersta 1:43      1
5000   Stora Kulltorp 2:2      1

[5001 rows x 2 columns]

In [5]:
col = "raa_id"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

raa_id: 5439 unique values

           raa_id  count
0             NaN   1841
1      Lockarp 18    223
2     Skänninge 5    121
3        Härad 82    119
4     Uppsala 614    107
...           ...    ...
5434   L2020:4793      1
5435          671      1
5436    L2018:146      1
5437   L2022:7402      1
5438    L2023:390      1

[5439 rows x 2 columns]

In [6]:
col = "site_type"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

site_type: 304 unique values

                   site_type  count
0                    Boplats   8449
1              Boplatsområde   6877
2    Grav- och boplatsområde   3390
3                   Gravfält   1884
4                Fossil åker   1059
..                       ...    ...
299       Gravfält, boplats,      1
300                     Grop      1
301    Boplatslämnuing övrig      1
302                Tegelbruk      1
303             Kyrka kapell      1

[304 rows x 2 columns]

In [7]:
col = "site_id"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

site_id: 6120 unique values

         site_id  count
0            NaN    338
1     L1988:4693    223
2      L2010:586    120
3     L1984:2122    119
4     L1941:4268    107
...          ...    ...
6115  L2020:4793      1
6116  L1982:4609      1
6117   L2018:146      1
6118  L2022:7402      1
6119   L2023:390      1

[6120 rows x 2 columns]

In [8]:
col = "uppdragsnummer"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

uppdragsnummer: 2876 unique values

     uppdragsnummer  count
0               NaN  13050
1         201901401    274
2         201700787    148
3         200800086    101
4         200100306    101
...             ...    ...
2871      202400331      1
2872      201400904      1
2873      200900594      1
2874      202000714      1
2875      200800209      1

[2876 rows x 2 columns]

In [9]:
col = "lab_id"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

lab_id: 30291 unique values

            lab_id  count
0         Ua-86040      3
1         Ua-10042      2
2         Ua-78697      2
3        Ua-26675a      2
4         Ua-43186      2
...            ...    ...
30286     LuS-6339      1
30287     16C/0261      1
30288  Beta-511943      1
30289     Ua-76281      1
30290     Ua-76282      1

[30291 rows x 2 columns]

In [10]:
col = "c14_age_bp"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

c14_age_bp: 4845 unique values

      c14_age_bp  count
0            NaN    345
1          250.0    179
2         1700.0     98
3         1740.0     89
4         1690.0     81
...          ...    ...
4840      8395.0      1
4841      2298.0      1
4842      2889.0      1
4843       909.0      1
4844     14575.0      1

[4845 rows x 2 columns]

In [11]:
col = "c14_error"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

c14_error: 223 unique values

     c14_error  count
0         30.0   5289
1         70.0   2155
2         40.0   1910
3         35.0   1862
4         60.0   1689
..         ...    ...
218      147.0      1
219      131.0      1
220      112.0      1
221      143.0      1
222        2.0      1

[223 rows x 2 columns]

In [12]:
col = "d13C"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

d13C: 730 unique values

       d13C  count
0       NaN  15862
1    -25.40    351
2    -25.60    344
3    -26.10    341
4    -26.40    328
..      ...    ...
725  -30.79      1
726  -25.14      1
727  -24.78      1
728 -224.40      1
729  -17.70      1

[730 rows x 2 columns]

In [13]:
col = "pMC_value"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

pMC_value: 73 unique values

    pMC_value  count
0         NaN  30201
1       100.0      5
2        99.3      4
3       101.6      3
4        99.5      3
..        ...    ...
68      119.9      1
69      109.1      1
70      104.7      1
71      106.9      1
72      144.6      1

[73 rows x 2 columns]

In [14]:
col = "pMC_error"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

pMC_error: 21 unique values

    pMC_error  count
0         NaN  30202
1        0.40     29
2        0.50     19
3        0.80     10
4        0.60      8
5        0.30      7
6        0.70      6
7        0.90      5
8        1.00      2
9        1.60      2
10       0.55      1
11       0.43      1
12      11.00      1
13       0.34      1
14       1.50      1
15       0.52      1
16       1.10      1
17       0.41      1
18       1.20      1
19      30.00      1
20       0.00      1

In [15]:
col = "c14_data_status"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

c14_data_status: 4 unique values

             c14_data_status  count
0                         ok  29731
1            c14_data_saknas    470
2  modern date, no c14 data.     99
3     orealistiskt_c14_värde      1

In [16]:
col = "comment"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

comment: 2058 unique values

                                                comment  count
0                                                   NaN  26619
1                               Daterar ej anläggningen    188
2         Viss oklarhet om vilket material som daterats     46
3                            14C-ålder saknas i rapport     37
4                                      Daterar ej huset     30
...                                                 ...    ...
2053  14C-ålder saknas i rapport. Kal. 2 sigma 1375-...      1
2054  14C-ålder saknas i rapport kal. 2 sigma 1730-1...      1
2055   Labnr saknas i rapport Kal. 2 sigma 1680-1515 BC      1
2056  14C-ålder saknas i rapport kaol. 2 sigma 1670-...      1
2057      14C-ålder saknas i  rapport Kal. 1690-1510 BC      1

[2058 rows x 2 columns]

In [17]:
col = "assessed_relevant"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

assessed_relevant: 4 unique values

  assessed_relevant  count
0                 J  28364
1                 N   1506
2                 X    235
3               NaN    196

In [18]:
col = "material"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

material: 42 unique values

                       material  count
0                        träkol  21891
1                 förkolnat frö   2667
2                  ben, obrända   1245
3                   ben, brända   1133
4                           trä   1087
5                  skalfragment    551
6           organisk beläggning    385
7                     växtdelar    334
8                          bark    302
9                         harts    253
10                         tand    155
11           frö (ej förkolnat)     36
12                    animalier     33
13                   kol i järn     30
14                     karbonat     27
15                        humus     24
16                        okänd     22
17                         horn     21
18                         torv     17
19                   sotig jord     17
20           organiskt material     15
21                         bröd      6
22                         kåda      6
23                     sediment      6
24                        mossa      5
25       sot/organiskt material      5
26           trä/bark/växtdelar      3
27                     kollagen      3
28                    förkolnad      3
29               skal/mollusker      3
30  ben, obränt karbonat frakt.      2
31                       pollen      2
32                    järnslagg      2
33                     ben,horn      2
34                     fekalier      1
35                        svamp      1
36                       gyttja      1
37                                   1
38                      stenkol      1
39              krossad keramik      1
40                         fisk      1
41                      kol/sot      1

In [19]:
col = "species"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

species: 544 unique values

               species  count
0                  NaN  12064
1                 tall   2929
2                björk   1955
3                   ek   1736
4               hassel   1649
..                 ...    ...
539     cf. Betula sp.      1
540         bark/näver      1
541        Populus sp.      1
542  Cyperaceae, snöre      1
543              haver      1

[544 rows x 2 columns]

In [20]:
col = "context_id"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

context_id: 10506 unique values

      context_id  count
0            NaN   4266
1             A1    718
2             A2    462
3             A3    333
4             A4    258
...          ...    ...
10501     A50440      1
10502     A50526      1
10503      A5836      1
10504      A5909      1
10505      A8793      1

[10506 rows x 2 columns]

In [21]:
col = "context_type"
vc = df[col].value_counts(dropna=False).reset_index().sort_values(by=col)
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

context_type: 962 unique values

         context_type  count
181   aktivitetslager      9
188     aktivitetsyta      8
469            ankare      2
337        anläggning      3
878  annan anläggning      1
..                ...    ...
304          åkervall      3
874           åkeryta      1
197         årderspår      7
925  östra golvgropen      1
7                 NaN    508

[962 rows x 2 columns]

In [22]:
col = "northing_3006"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

northing_3006: 6173 unique values

      northing_3006  count
0           6157001    223
1           6472725    120
2           6581472    119
3           6642663    107
4           6642832    106
...             ...    ...
6168        6482458      1
6169        6538022      1
6170        6543544      1
6171        6543568      1
6172        6543765      1

[6173 rows x 2 columns]

In [23]:
col = "easting_3006"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

easting_3006: 6149 unique values

      easting_3006  count
0           375846    223
1           505067    120
2           607657    119
3           648609    107
4           647453    106
...            ...    ...
6144        284212      1
6145        551529      1
6146        564279      1
6147        550473      1
6148        550513      1

[6149 rows x 2 columns]

In [24]:
col = "longitude"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

longitude: 6212 unique values

      longitude  count
0     13.032330    223
1     15.086680    120
2     16.893721    119
3     17.656345    107
4     17.635827    106
...         ...    ...
6207  11.303832      1
6208  15.896363      1
6209  16.119718      1
6210  15.879265      1
6211  15.880007      1

[6212 rows x 2 columns]

In [25]:
col = "latitude"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

latitude: 6211 unique values

       latitude  count
0     55.543218    223
1     58.395302    120
2     59.358220    119
3     59.894680    107
4     59.896610    106
...         ...    ...
6206  58.429458      1
6207  58.978667      1
6208  59.026524      1
6209  59.028593      1
6210  59.030358      1

[6211 rows x 2 columns]

In [26]:
col = "location_precision"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

location_precision: 2 unique values

    location_precision  count
0  archaeological site  29963
1               parish    338

In [27]:
col = "cal_68_min"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

cal_68_min: 2837 unique values

      cal_68_min  count
0            NaN    570
1         1950.0    542
2          773.0    276
3          772.0    254
4          534.0    176
...          ...    ...
2832     -7953.0      1
2833     -7683.0      1
2834     -7362.0      1
2835     -7587.0      1
2836    -15826.0      1

[2837 rows x 2 columns]

In [28]:
col = "cal_68_max"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

cal_68_max: 2936 unique values

      cal_68_max  count
0            NaN    570
1          775.0    411
2          776.0    276
3          266.0    224
4          435.0    199
...          ...    ...
2931     -8160.0      1
2932     -8226.0      1
2933     -7588.0      1
2934     -7537.0      1
2935    -15989.0      1

[2936 rows x 2 columns]

In [29]:
col = "cal_95_min"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

cal_95_min: 2810 unique values

      cal_95_min  count
0         1950.0   1020
1            NaN    570
2          773.0    313
3          772.0    171
4          402.0    167
...          ...    ...
2805     -7533.0      1
2806     -7600.0      1
2807     -7581.0      1
2808     -1417.0      1
2809    -15616.0      1

[2810 rows x 2 columns]

In [30]:
col = "cal_95_max"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

cal_95_max: 2904 unique values

      cal_95_max  count
0            NaN    570
1          775.0    297
2          776.0    280
3          434.0    147
4          250.0    125
...          ...    ...
2899     -8545.0      1
2900     -8204.0      1
2901     -8200.0      1
2902     -8254.0      1
2903    -16071.0      1

[2904 rows x 2 columns]

In [31]:
col = "median_cal_year"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

median_cal_year: 5798 unique values

      median_cal_year  count
0                 NaN    570
1              1562.0    155
2              1347.0    107
3              -277.0    106
4              -276.0    100
...               ...    ...
5793          -7644.0      1
5794          -1738.0      1
5795           -416.0      1
5796         -15902.0      1
5797          -1546.0      1

[5798 rows x 2 columns]

In [32]:
col = "calibration_method"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

calibration_method: 2 unique values

             calibration_method  count
0  HPD; IntCal20; rcarbon 1.5.0  29731
1                           NaN    570

In [33]:
col = "calibration_status"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

calibration_status: 3 unique values

  calibration_status  count
0         calibrated  29731
1   not calibratable    569
2  not yet attempted      1

In [34]:
col = "author"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

author: 1898 unique values

                                      author  count
0                                  Protokoll    485
1                              Strömberg, Bo    277
2                          Olausson, Michael    261
3                              Carlsson, Tom    208
4                             Åstrand, Johan    178
...                                      ...    ...
1893       Ängeby, Gisela & Nordqvist, Bengt      1
1894  Bramstång, Carina & Gustafsson, Agneta      1
1895                           Pye, Jonathan      1
1896          Vajking, Erik & Swedberg, Stig      1
1897  Larsson, G., Sundström, L & Guinard, M      1

[1898 rows x 2 columns]

In [35]:
col = "publication_year"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

publication_year: 67 unique values

    publication_year  count
0             2006.0   1555
1             2014.0   1321
2             2005.0   1283
3             1996.0   1261
4             2017.0   1196
..               ...    ...
62            1985.0      6
63             198.0      4
64            1966.0      4
65             200.0      4
66             201.0      1

[67 rows x 2 columns]

In [36]:
col = "title"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

title: 4497 unique values

                                                  title  count
0                                       C-14 Dateringar    485
1     Järnhantering på boplatser i Halland under äld...    236
2     Norra Spånga. Bebyggelse och samhälle under jä...    149
3     Östra Odarslöv 13:5, ESS-området Forntid möter...    148
4     Det inneslutna rummet-om kultiska hägnader, fo...    145
...                                                 ...    ...
4492  Tossene 371 och 1042. Tossene socken, Sotenäs ...      1
4493  Klippöverhäng och stenåldersboplats vid Åby sä...      1
4494  Tossene 137 och 576 inom Valla 4:7 och 5:1, To...      1
4495  Tossene L2020:4793 och L2020:4796, Sotenäs kom...      1
4496  Stockbåten i Lyttersta. Arkeologisk dokumentat...      1

[4497 rows x 2 columns]

In [37]:
col = "journal"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

journal: 4299 unique values

                                                journal  count
0                                               Stencil    546
1                                                   NaN    468
2         Nya bidrag till Hallands äldsta historia nr 4    236
3                          Stockholmsmonografier vol 76    149
4                         Arkeologerna, Rapport 2017:11    148
...                                                 ...    ...
4294                Kulturlandskapet rapporter, 2014:13      1
4295                      UV Väst, Internrapport 1993:4      1
4296  Rio Kulturkooperativ, Kulturhistoriska rapport...      1
4297                Kulturlandskapet rapporter, 2020:14      1
4298                                 SAU Rapport 2008:7      1

[4299 rows x 2 columns]

In [38]:
col = "place_of_publication"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

place_of_publication: 141 unique values

             place_of_publication  count
0                       Stockholm   6400
1                         Uppsala   3106
2                            Lund   2814
3                       Linköping   2553
4                        Västerås   1314
..                            ...    ...
136                         Örero      1
137                    Skellefteå      1
138                      Arjeplog      1
139  Uppsala. Rapport 2: Uppsala.      1
140                     Västeråsd      1

[141 rows x 2 columns]

### Look for rows with more than one site_id in the value

In [39]:
df[df['site_id'].isin(['L1988:6073, L1988:6685','L1983:7553, L1983:7552, L1983:8196, L1983:7619'])]

,socken,landskap,place_name,raa_id,site_type,site_id,uppdragsnummer,lab_id,c14_age_bp,c14_error,...,cal_95_min,cal_95_max,median_cal_year,calibration_method,calibration_status,author,publication_year,title,journal,place_of_publication
2062,Åker,Södermanland,Järsta 1:3,Åker 267,Boplats,"L1983:7553, L1983:7552, L1983:8196, L1983:7619",NaN,ST13672,1940.0,60.0,...,230.0,-44.0,89.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Franzén, Bitte & Schützler, Lillemor",2000.0,Fornlämningar vid Albertsro.,"UV Mitt, Rapport 2000:37",Stockholm
2063,Åker,Södermanland,Järsta 1:3,Åker 267,Boplats,"L1983:7553, L1983:7552, L1983:8196, L1983:7619",NaN,ST13673,1870.0,60.0,...,329.0,19.0,168.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Franzén, Bitte & Schützler, Lillemor",2000.0,Fornlämningar vid Albertsro.,"UV Mitt, Rapport 2000:37",Stockholm
2064,Åker,Södermanland,Järsta 1:3,Åker 267,Boplats,"L1983:7553, L1983:7552, L1983:8196, L1983:7619",NaN,ST13675,1790.0,45.0,...,400.0,130.0,283.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Franzén, Bitte & Schützler, Lillemor",2000.0,Fornlämningar vid Albertsro.,"UV Mitt, Rapport 2000:37",Stockholm
2065,Åker,Södermanland,Järsta 1:3,Åker 267,Boplats,"L1983:7553, L1983:7552, L1983:8196, L1983:7619",NaN,ST13676,2130.0,40.0,...,-44.0,-351.0,-151.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Franzén, Bitte & Schützler, Lillemor",2000.0,Fornlämningar vid Albertsro.,"UV Mitt, Rapport 2000:37",Stockholm
2094,Åker,Södermanland,Järsta 1:3,Åker 267,Boplats,"L1983:7553, L1983:7552, L1983:8196, L1983:7619",NaN,ST14211,1545.0,45.0,...,601.0,421.0,518.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Franzén, Bitte & Schützler, Lillemor",2000.0,Fornlämningar vid Albertsro.,"UV Mitt, Rapport 2000:37",Stockholm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26390,Stora Herrestad,Skåne,Herrestad 68:88 m fl,"Stora Herrestad 60:1, 60:2",Boplatsområde,"L1988:6073, L1988:6685",000100475,Ua-7927,2025.0,70.0,...,202.0,-338.0,-17.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Andersson, Magnus m fl",1999.0,Boplats stenålder-äldre järnålder.,"UV Syd, Rapport 1999:8",Lund
26391,Stora Herrestad,Skåne,Herrestad 68:88 m fl,"Stora Herrestad 60:1, 60:2",Boplatsområde,"L1988:6073, L1988:6685",000100475,Ua-7928,1930.0,65.0,...,242.0,-48.0,100.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Andersson, Magnus m fl",1999.0,Boplats stenålder-äldre järnålder.,"UV Syd, Rapport 1999:8",Lund
26392,Stora Herrestad,Skåne,Herrestad 68:88 m fl,"Stora Herrestad 60:1, 60:2",Boplatsområde,"L1988:6073, L1988:6685",000100475,Ua-7929,4055.0,80.0,...,-2350.0,-2878.0,-2612.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Andersson, Magnus m fl",1999.0,Boplats stenålder-äldre järnålder.,"UV Syd, Rapport 1999:8",Lund
26393,Stora Herrestad,Skåne,Herrestad 68:88 m fl,"Stora Herrestad 60:1, 60:2",Boplatsområde,"L1988:6073, L1988:6685",000100475,Ua-7930,3285.0,70.0,...,-1421.0,-1738.0,-1562.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Andersson, Magnus m fl",1999.0,Boplats stenålder-äldre järnålder.,"UV Syd, Rapport 1999:8",Lund
26394,Stora Herrestad,Skåne,Herrestad 68:88 m fl,"Stora Herrestad 60:1, 60:2",Boplatsområde,"L1988:6073, L1988:6685",000100475,Ua-7931,3435.0,145.0,...,-1425.0,-2135.0,-1750.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Andersson, Magnus m fl",1999.0,Boplats stenålder-äldre järnålder.,"UV Syd, Rapport 1999:8",Lund

### Extract unique `landskap` values for a manual resolution to be created

A handful of `landskap` values are abbreviations/typos of a full province name already present
elsewhere in the column (e.g. `Bo` vs `Bohuslän`, `Vg`/`vg` vs `Västergötland`, `Sk` vs `Skåne`).
Export the raw value counts as the starting point for a hand-curated
`landskap_manual_resolution.csv`, same pattern as `material_manual_resolution.csv`'s origin in
`archive/notebooks/material_counts.ipynb`.

In [40]:
from pathlib import Path

landskap_counts = df['landskap'].value_counts(dropna=False).reset_index()
landskap_counts.columns = ['landskap', 'count']
print(f'{len(landskap_counts)} unique landskap values')

OUTPUT_DIR = Path('../output/landskap')
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
landskap_counts.to_csv(OUTPUT_DIR / 'landskap_counts.csv', index=False)

landskap_counts

36 unique landskap values

         landskap  count
0         Uppland   6042
1           Skåne   4780
2    Östergötland   3212
3    Södermanland   2942
4         Halland   1835
5        Bohuslän   1773
6         Småland   1760
7           Närke   1321
8   Västergötland   1262
9     Västmanland   1247
10        Dalarna    669
11       Blekinge    563
12       Värmland    379
13     Norrbotten    328
14        Gotland    294
15       Lappland    293
16       Medelpad    269
17          Öland    236
18       Jämtland    214
19             Bo    173
20   Ångermanland    116
21     Härjedalen    108
22    Hälsingland     88
23    Gästrikland     83
24             Vg     81
25             Ha     79
26   Västerbotten     42
27             Sm     39
28             Sk     18
29       Dalsland     16
30             Sö     15
31             Nä     11
32             vg      5
33             Vs      3
34             Up      3
35             Ög      2

Let's check for information in the rows for those values to be resolved.

In [41]:
df[df['landskap'].isin(['Bo', 'Ha', 'Nä', 'Ög', 'Sk', 'Sm', 'Sö', 'Up', 'Vg', 'vg', 'Vs'])]

,socken,landskap,place_name,raa_id,site_type,site_id,uppdragsnummer,lab_id,c14_age_bp,c14_error,...,cal_95_min,cal_95_max,median_cal_year,calibration_method,calibration_status,author,publication_year,title,journal,place_of_publication
29859,Arboga socken,Vs,Jäder 1: 15,65,Stensättning,L2002:5029,000102567,Ua-10042,970.0,75.0,...,1223.0,897.0,1089.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Ljungqvist, Henrik",1995.0,"En gravgrupp, Raä 65. Jäder 1:15, Arboga lands...","Arkeologikonsult, Slutundersökingsrapport 1995:8",Upplands Väsby
29860,Arboga socken,Vs,Jäder 1: 15,65,Stensättning,L2002:5029,000102567,Ua-10043,850.0,75.0,...,1278.0,1037.0,1182.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Ljungqvist, Henrik",1995.0,"En gravgrupp, Raä 65. Jäder 1:15, Arboga lands...","Arkeologikonsult, Slutundersökingsrapport 1995:8",Upplands Väsby
29861,Aringsås,Sm,Spåningslanda 4:3,185,Kolningsanläggning,L1951:152,201802010,Ua-57828,127.0,29.0,...,1941.0,1674.0,1836.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Engman, Fredrik & Säfström, Simon",2018.0,Arkeologisk förundersökning. Fossil åker Aring...,Uppdragsnummer 13002557_2018-05-09;,Stockholm
29862,Aringsås,Sm,Spåningslanda 4:3,186,Härd,L1951:157,201802010,Ua-57829,2447.0,31.0,...,-410.0,-751.0,-557.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Engman, Fredrik & Säfström, Simon",2018.0,Arkeologisk förundersökning. Fossil åker Aring...,Uppdragsnummer 13002557_2018-05-09;,Stockholm
29863,Aringsås,Sm,Aringsås 15:1,59,Röse,L1955:9698,202100141,Ua-68762,1856.0,30.0,...,244.0,87.0,183.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Nilsson, Nicholas",2021.0,Förundersökning av röse samt angränsande mark,"Museiarkeologi Sydost, Rapport 2021:02",Kalmar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30296,Västra Vingåker,Sö,Sävstaholm 2:325,79,Gravfält,L1983:6225,NaN,16CB/0263,1230.0,20.0,...,880.0,692.0,804.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Hed Jakobsson, Anna",2016.0,Ett gravfält och en stenåldersboplats i Vingåk...,"Rapporter från Arkeologikonsult, 2016:2936",Upplands Väsby
30297,Västra Vingåker,Sö,Stora Kulltorp 2:2,L2018:146,Härd,L2018:146,201800973,Beta-511943,2820.0,30.0,...,-898.0,-1104.0,-971.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Strengbom, Erica",2019.0,Schaktningsövervakning i Västra Vingåker,"Arkeologgruppen AB, Rapport 2019:08",Örebro
30298,Västra Vingåker,Sö,Sävstaholm 2:382,L2022:7402,Boplatslämning övrig,L2022:7402,202200776,Ua-76281,259.0,30.0,...,1950.0,1519.0,1646.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Holm, Jenny",2023.0,Solcellspark vid Sävstaholm. Arkeologisk utred...,"Stiftelsen Kulturmiljövår, rapport, 2023:52",Västerås
30299,Västra Vingåker,Sö,Sävstaholm 2:382,L2023:390,Boplatslämning övrig,L2023:390,202200776,Ua-76282,1700.0,31.0,...,418.0,253.0,362.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Holm, Jenny",2023.0,Solcellspark vid Sävstaholm. Arkeologisk utred...,"Stiftelsen Kulturmiljövår, rapport, 2023:52",Västerås
30300,Arboga socken,Vs,Jäder 1: 15,65,Stensättning,L2002:5029,000102567,Ua-10042,970.0,75.0,...,1223.0,897.0,1089.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Ljungqvist, Henrik",1995.0,"En gravgrupp, Raä 65. Jäder 1:15, Arboga lands...","Arkeologikonsult, Slutundersökingsrapport 1995:8",Upplands Väsby

In [42]:
# there seems to be an error for similar title and different socken and landskap
error_df = df[df['title']=='Arkeologisk förundersökning. Fossil åker Aringsås 77:1. Aringsås socken i Alvesta kommun, Kronobergs län']
error_df

,socken,landskap,place_name,raa_id,site_type,site_id,uppdragsnummer,lab_id,c14_age_bp,c14_error,...,cal_95_min,cal_95_max,median_cal_year,calibration_method,calibration_status,author,publication_year,title,journal,place_of_publication
29861,Aringsås,Sm,Spåningslanda 4:3,185,Kolningsanläggning,L1951:152,201802010,Ua-57828,127.0,29.0,...,1941.0,1674.0,1836.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Engman, Fredrik & Säfström, Simon",2018.0,Arkeologisk förundersökning. Fossil åker Aring...,Uppdragsnummer 13002557_2018-05-09;,Stockholm
29862,Aringsås,Sm,Spåningslanda 4:3,186,Härd,L1951:157,201802010,Ua-57829,2447.0,31.0,...,-410.0,-751.0,-557.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Engman, Fredrik & Säfström, Simon",2018.0,Arkeologisk förundersökning. Fossil åker Aring...,Uppdragsnummer 13002557_2018-05-09;,Stockholm
29865,Aringsås,Sm,Spåningslanda 4:3,77,Fossil åker,L1955:9245,201802010,Ua-57820,147.0,30.0,...,1948.0,1669.0,1810.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Engman, Fredrik & Säfström, Simon",2018.0,Arkeologisk förundersökning. Fossil åker Aring...,Uppdragsnummer 13002557_2018-05-09;,Stockholm
29866,Aringsås,Sm,Spåningslanda 4:3,77,Fossil åker,L1955:9245,201802010,Ua-57821,3514.0,32.0,...,-1745.0,-1929.0,-1828.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Engman, Fredrik & Säfström, Simon",2018.0,Arkeologisk förundersökning. Fossil åker Aring...,Uppdragsnummer 13002557_2018-05-09;,Stockholm
29867,Aringsås,Sm,Spåningslanda 4:3,77,Fossil åker,L1955:9245,201802010,Ua-57822,14.0,31.0,...,1915.0,1696.0,1828.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Engman, Fredrik & Säfström, Simon",2018.0,Arkeologisk förundersökning. Fossil åker Aring...,Uppdragsnummer 13002557_2018-05-09;,Stockholm
29868,Aringsås,Sm,Spåningslanda 4:3,77,Fossil åker,L1955:9245,201802010,Ua-57823,92.0,29.0,...,1925.0,1688.0,1836.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Engman, Fredrik & Säfström, Simon",2018.0,Arkeologisk förundersökning. Fossil åker Aring...,Uppdragsnummer 13002557_2018-05-09;,Stockholm
29869,Aringsås,Sm,Spåningslanda 4:3,77,Fossil åker,L1955:9245,201802010,Ua-57824,64.0,30.0,...,1917.0,1694.0,1831.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Engman, Fredrik & Säfström, Simon",2018.0,Arkeologisk förundersökning. Fossil åker Aring...,Uppdragsnummer 13002557_2018-05-09;,Stockholm
29870,Aringsås,Sm,Spåningslanda 4:3,77,Fossil åker,L1955:9245,201802010,Ua-57825,1900.0,30.0,...,225.0,63.0,147.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Engman, Fredrik & Säfström, Simon",2018.0,Arkeologisk förundersökning. Fossil åker Aring...,Uppdragsnummer 13002557_2018-05-09;,Stockholm
29871,Aringsås,Sm,Spåningslanda 4:3,77,Fossil åker,L1955:9245,201802010,Ua-57826,2718.0,31.0,...,-808.0,-918.0,-862.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Engman, Fredrik & Säfström, Simon",2018.0,Arkeologisk förundersökning. Fossil åker Aring...,Uppdragsnummer 13002557_2018-05-09;,Stockholm
29872,Aringsås,Sm,Spåningslanda 4:3,77,Fossil åker,L1955:9245,201802010,Ua-57827,2864.0,32.0,...,-924.0,-1184.0,-1034.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Engman, Fredrik & Säfström, Simon",2018.0,Arkeologisk förundersökning. Fossil åker Aring...,Uppdragsnummer 13002557_2018-05-09;,Stockholm
29879,Bogsta,Sö,Ekla 1:5,78,Boplats,L1985:5239,201802010,Ua-81693,4255.0,31.0,...,-2704.0,-2916.0,-2887.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Engman, Fredrik & Säfström, Simon",2018.0,Arkeologisk förundersökning. Fossil åker Aring...,Uppdragsnummer 13002557_2018-05-09;,Stockholm

In [43]:
df.iloc[29872:29882].to_excel('../output/socken_landskap_title_question.xlsx') 
error_df.to_excel('../output/Aringsås_study_mistake.xlsx')

We could also assume that they are abbreviations and infer what landskap they are refering to, but for the particular case of Vs that could refer to Västerbotten, Västmanland and Västergötland, it is better to take the time to check this before assumming correct resolutions.
- Vs -> Västmanland
- Sm -> Småland
- Bo -> Bohuslän
-

### Extract `lab_id` prefixes and match against `tbl_dating_labs`

Same approach as the `lab_no` matching done in `archive/notebooks/explore.ipynb` for
`c14_master_v08.xlsx`, adapted to this dataset's `lab_id` column. The *prefix* of `lab_id`
(the letters before the dash/number, e.g. `Ua` in `Ua-49252`) should correspond to a lab's
`international_lab_id` in `tbl_dating_labs`. We keep the full `lab_id` string as-is, but use
the prefix to resolve each row to a SEAD `dating_lab_id`. The end of this section exports a
full prefix-to-lab mapping for manual review, since not every value can be resolved
automatically.

In [44]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path('../..').resolve()))
from shared.resolution import common

# .env lives at the true repo root, two levels up from current/notebooks/.
engine = common.get_db_engine('../../.env')

dating_labs = pd.read_sql(
    "select dating_lab_id, international_lab_id, lab_name from public.tbl_dating_labs",
    engine,
)
print(f"{len(dating_labs)} labs in sead_staging")
dating_labs.head()

234 labs in sead_staging

,dating_lab_id,international_lab_id,lab_name
0,685,A,Arizona
1,686,AA,NSF
2,687,AAR,University of Aarhus
3,688,AC,Ingeis
4,689,AECV,Alberta Environmental Center of Vegreville

#### Extracting the prefix

Not every `lab_id` follows the `<prefix>-<number>` pattern, so the parser below sorts every
row into one of three categories instead of silently dropping the awkward ones:

- **`standard`** -- a normal `<letters><separator><number>` value, e.g. `Ua-49252`. A handful
  of these spell out `Okänd` (Swedish for "unknown") in place of the accession number, e.g.
  `Ua-Okänd62` or `ICA-Okänd 2` -- the lab is still known, only the specific sample number is
  missing, so `Okänd<number>` is stripped out before reading the prefix.
- **`unknown_no_lab`** -- `lab_id` is literally just `Okänd ###` with no lab code at all -- a
  genuinely unknown lab.
- **`non_standard_id`** -- ids like `17C/0902` or `14C-5261` that don't start with a letter at
  all. These look like an internal accession scheme (year + a 1-2 letter sample-type code +
  sequence number), not an international lab code, so no lab can be derived from them.

In [45]:
import re

def lab_id_prefix(lab_id):
    s = str(lab_id)
    # "Okänd<number>" means the *sample number* is unknown, not the lab -- drop it before
    # reading the prefix, e.g. "Ua-Okänd62" -> "Ua"
    core = re.sub(r"[-\s]?[Oo]k[äa]nd\s*\d*", "", s)
    leading = re.match(r"^[A-Za-z]+", core)
    if leading:
        return leading.group(0), "standard"
    if core.strip() == "":
        return "(Okänd -- no lab given at all)", "unknown_no_lab"
    # no leading letter, but there might be one buried in there (e.g. the "C" in "17C/0902")
    embedded = re.search(r"[A-Za-z]+", core)
    tag = embedded.group(0) if embedded else "?"
    return f"~{tag} (embedded, not a leading prefix)", "non_standard_id"

parsed = df["lab_id"].apply(lab_id_prefix)
df["lab_id_prefix"] = parsed.apply(lambda t: t[0])
df["lab_id_prefix_category"] = parsed.apply(lambda t: t[1])
df["lab_id_prefix_category"].value_counts()

lab_id_prefix_category
standard           29640
non_standard_id      576
unknown_no_lab        85
Name: count, dtype: int64

#### Matching prefixes against `international_lab_id`

Only `standard`-category prefixes are matchable at all. `international_lab_id` isn't
consistently cased against this dataset, and some codes carry a trailing `*` (the
*Radiocarbon* journal convention for a lab that's no longer active) that this dataset never
has. Match in three tiers -- exact, case-insensitive, and case-insensitive with the trailing
`*` stripped -- and record which tier each prefix matched on, so low-confidence matches stay
visible instead of being silently accepted.

In [46]:
exact = dict(zip(dating_labs["international_lab_id"], dating_labs["dating_lab_id"]))
by_lower = {code.lower(): (code, lab_id) for code, lab_id in exact.items()}
by_lower_stripped = {code.rstrip("*").lower(): (code, lab_id) for code, lab_id in exact.items()}

def match_lab(prefix, category):
    if category != "standard":
        return pd.Series([None, None, None])
    if prefix in exact:
        return pd.Series([exact[prefix], prefix, "exact"])
    hit = by_lower.get(prefix.lower())
    if hit:
        return pd.Series([hit[1], hit[0], "case_insensitive"])
    hit = by_lower_stripped.get(prefix.rstrip("*").lower())
    if hit:
        return pd.Series([hit[1], hit[0], "stripped_star"])
    return pd.Series([None, None, None])

prefix_matches = (
    df.groupby(["lab_id_prefix", "lab_id_prefix_category"])
    .agg(n_rows=("lab_id", "size"),
         example_lab_id=("lab_id", lambda s: "; ".join(sorted(s.astype(str).unique())[:3])))
    .reset_index()
)
prefix_matches[["dating_lab_id", "matched_international_lab_id", "match_type"]] = prefix_matches.apply(
    lambda r: match_lab(r["lab_id_prefix"], r["lab_id_prefix_category"]), axis=1,
)
lab_name_by_id = dict(zip(dating_labs["dating_lab_id"], dating_labs["lab_name"]))
prefix_matches["matched_lab_name"] = prefix_matches["dating_lab_id"].map(lab_name_by_id)
prefix_matches = prefix_matches.sort_values("n_rows", ascending=False).reset_index(drop=True)
prefix_matches

,lab_id_prefix,lab_id_prefix_category,n_rows,example_lab_id,dating_lab_id,matched_international_lab_id,match_type,matched_lab_name
0,Ua,standard,19691,Ua--15661; Ua-10022; Ua-10023,882.0,Ua,exact,Uppsala Accelerator
1,ST,standard,3622,ST10; ST10006; ST10008,864.0,St*,stripped_star,Stockholm
2,Beta,standard,2954,Beta--48629; Beta-100264; Beta-100265,700.0,Beta,exact,Beta Analytic
3,Poz,standard,749,Poz-10046; Poz-10047; Poz-10048,831.0,Poz,exact,Poznan Radiocarbon Laboratory
4,Lu,standard,492,Lu-100; Lu-1005; Lu-1006,791.0,Lu,exact,Lund
5,"~C (embedded, not a leading prefix)",non_standard_id,488,12C/0126; 14C-5261; 14C-5262,NaN,NaN,NaN,NaN
6,GrN,standard,367,GrN-19822; GrN-19823; GrN-19824,743.0,GrN,exact,Groningen
7,LuS,standard,357,LuS-10031; LuS-10069; LuS-10070,915.0,LUS,case_insensitive,Lund University
8,LTL,standard,308,LTL 14001A; LTL-14001A; LTL-14040A,NaN,NaN,NaN,NaN
9,LuA,standard,198,LuA-110; LuA-3750; LuA-3752,NaN,NaN,NaN,NaN
10,T,standard,160,T-10063; T-10111; T-10112,868.0,T,exact,Trondheim
11,U,standard,132,U-1006; U-1010; U-1011,881.0,U,exact,Uppsala
12,KIA,standard,100,KIA-14416; KIA-14417; KIA-14418,778.0,KIA,exact,Kiel AMS
13,KI,standard,97,KI-1300; KI-2287; KI-2289,777.0,KI,exact,Kiel
14,(Okänd -- no lab given at all),unknown_no_lab,85,Okänd 109; Okänd 110; Okänd 111,NaN,NaN,NaN,NaN
15,UGAMS,standard,72,UGAMS-10871; UGAMS-10872; UGAMS-10873,NaN,NaN,NaN,NaN
16,GrA,standard,70,GrA-13503; GrA-13517; GrA-14136,742.0,GrA,exact,Groningen Accelerator
17,UtC,standard,54,UtC-1469; UtC-1470; UtC-1471,896.0,UtC,exact,Utrecht van der Graaf Laboratorium
18,UBA,standard,48,UBA-16601; UBA-20881; UBA-21057,913.0,UBA,exact,Belfast
19,"~P (embedded, not a leading prefix)",non_standard_id,42,15P/0701; 15P/1027; 15P/1202,NaN,NaN,NaN,NaN
20,MAMS,standard,28,MAMS-18822; MAMS-18823; MAMS-18824,NaN,NaN,NaN,NaN
21,AAR,standard,27,"AAR-18430,1; AAR-18430,2; AAR-18431,1",687.0,AAR,exact,University of Aarhus
22,CAIS,standard,26,CAIS-4751; CAIS-4752; CAIS-4753,NaN,NaN,NaN,NaN
23,"~W (embedded, not a leading prefix)",non_standard_id,20,15W/0651; 16W/0602; 16W/0603,NaN,NaN,NaN,NaN
24,MKL,standard,18,MKL-4120; MKL-4121; MKL-4122,NaN,NaN,NaN,NaN
25,"~B (embedded, not a leading prefix)",non_standard_id,10,16B/1251; 16B/1252; 17B/0142,NaN,NaN,NaN,NaN
26,NZA,standard,9,NZA-19401; NZA-I9403; NZA-I9404,818.0,NZA,exact,New Zealand
27,CAMS,standard,8,CAMS-5359; CAMS-5650; CAMS-5651,709.0,CAMS,exact,Center for Accelerator Mass Spectrometry
28,UGA,standard,7,UGA-14067; UGA-14068; UGA-14069,890.0,UGa,case_insensitive,University of Georgia
29,Tln,standard,7,Tln-2408; Tln-2613; Tln-2614,877.0,Tln,exact,Tallinn
30,Lus,standard,6,Lus-13431; Lus-7253; Lus-7254,915.0,LUS,case_insensitive,Lund University
31,WK,standard,6,WK-16542; WK-9081; WK-9082,903.0,Wk,case_insensitive,University of Waikato
32,"~M (embedded, not a leading prefix)",non_standard_id,5,16M/0502; 16M/0503; 16M/0505,NaN,NaN,NaN,NaN
33,"~O (embedded, not a leading prefix)",non_standard_id,5,19O/0186; 19O/0187; 19O/0188,NaN,NaN,NaN,NaN
34,Lua,standard,5,Lua-4541; Lua-5360; Lua-5363,NaN,NaN,NaN,NaN
35,"~T (embedded, not a leading prefix)",non_standard_id,4,15T/1001; 15T/1002; 18T/0301,NaN,NaN,NaN,NaN
36,Hel,standard,3,Hel-4536; Hel-4541; Hel-4542,752.0,Hel,exact,Helsinki
37,ICA,standard,3,ICA-Okänd 1; ICA-Okänd 2; ICA-Okänd 3,NaN,NaN,NaN,NaN
38,AA,standard,2,AA-1845; AA-1846,686.0,AA,exact,NSF
39,UCLA,standard,2,UCLA-2463F; UCLA-2763B,887.0,UCLA,exact,"University of California, Los Angeles"
40,Ki,standard,2,Ki-2477; Ki-3336,777.0,KI,case_insensitive,Kiel
41,KlA,standard,2,KlA-37032; KlA-37033,NaN,NaN,NaN,NaN
42,OxA,standard,2,OxA-2789; OxA-2792,824.0,OxA,exact,Oxford Radiocarbon Accelerator Unit
43,"~CB (embedded, not a leading prefix)",non_standard_id,2,16CB/0263,NaN,NaN,NaN,NaN
44,ETH,standard,1,ETH-7379,728.0,ETH,exact,ETH/AMS Facility
45,Grn,standard,1,Grn-24657,743.0,GrN,case_insensitive,Groningen
46,Tua,standard,1,Tua-2720,NaN,NaN,NaN,NaN
47,SUERC,standard,1,SUERC-84952,918.0,SUERC,exact,Scottish Universities Environmental Research C...
48,ua,standard,1,ua-26484,882.0,Ua,case_insensitive,Uppsala Accelerator
49,VERA,standard,1,VERA-5148,912.0,VERA,exact,Institut für Radiumforschung und Kernphysik

In [47]:
matched_mask = prefix_matches["dating_lab_id"].notna()
by_type = prefix_matches.groupby("match_type", dropna=False)["n_rows"].sum().sort_values(ascending=False)
total_matched = prefix_matches.loc[matched_mask, "n_rows"].sum()
print(f"{total_matched} / {len(df)} rows ({total_matched / len(df):.1%}) resolve to a SEAD dating_lab_id")
print()
print("rows by match_type (NaN = unresolved):")
print(by_type)
print()
print("prefixes with a real-looking lab code but no match in tbl_dating_labs (candidates to add to SEAD):")
prefix_matches[prefix_matches["lab_id_prefix"].notna() & ~matched_mask].sort_values("n_rows", ascending=False)

28979 / 30301 rows (95.6%) resolve to a SEAD dating_lab_id

rows by match_type (NaN = unresolved):
match_type
exact               24977
stripped_star        3622
NaN                  1322
case_insensitive      380
Name: n_rows, dtype: int64

prefixes with a real-looking lab code but no match in tbl_dating_labs (candidates to add to SEAD):

,lab_id_prefix,lab_id_prefix_category,n_rows,example_lab_id,dating_lab_id,matched_international_lab_id,match_type,matched_lab_name
5,"~C (embedded, not a leading prefix)",non_standard_id,488,12C/0126; 14C-5261; 14C-5262,NaN,NaN,NaN,NaN
8,LTL,standard,308,LTL 14001A; LTL-14001A; LTL-14040A,NaN,NaN,NaN,NaN
9,LuA,standard,198,LuA-110; LuA-3750; LuA-3752,NaN,NaN,NaN,NaN
14,(Okänd -- no lab given at all),unknown_no_lab,85,Okänd 109; Okänd 110; Okänd 111,NaN,NaN,NaN,NaN
15,UGAMS,standard,72,UGAMS-10871; UGAMS-10872; UGAMS-10873,NaN,NaN,NaN,NaN
19,"~P (embedded, not a leading prefix)",non_standard_id,42,15P/0701; 15P/1027; 15P/1202,NaN,NaN,NaN,NaN
20,MAMS,standard,28,MAMS-18822; MAMS-18823; MAMS-18824,NaN,NaN,NaN,NaN
22,CAIS,standard,26,CAIS-4751; CAIS-4752; CAIS-4753,NaN,NaN,NaN,NaN
23,"~W (embedded, not a leading prefix)",non_standard_id,20,15W/0651; 16W/0602; 16W/0603,NaN,NaN,NaN,NaN
24,MKL,standard,18,MKL-4120; MKL-4121; MKL-4122,NaN,NaN,NaN,NaN
25,"~B (embedded, not a leading prefix)",non_standard_id,10,16B/1251; 16B/1252; 17B/0142,NaN,NaN,NaN,NaN
32,"~M (embedded, not a leading prefix)",non_standard_id,5,16M/0502; 16M/0503; 16M/0505,NaN,NaN,NaN,NaN
33,"~O (embedded, not a leading prefix)",non_standard_id,5,19O/0186; 19O/0187; 19O/0188,NaN,NaN,NaN,NaN
34,Lua,standard,5,Lua-4541; Lua-5360; Lua-5363,NaN,NaN,NaN,NaN
35,"~T (embedded, not a leading prefix)",non_standard_id,4,15T/1001; 15T/1002; 18T/0301,NaN,NaN,NaN,NaN
37,ICA,standard,3,ICA-Okänd 1; ICA-Okänd 2; ICA-Okänd 3,NaN,NaN,NaN,NaN
41,KlA,standard,2,KlA-37032; KlA-37033,NaN,NaN,NaN,NaN
43,"~CB (embedded, not a leading prefix)",non_standard_id,2,16CB/0263,NaN,NaN,NaN,NaN
46,Tua,standard,1,Tua-2720,NaN,NaN,NaN,NaN

#### Possible-match suggestions and a full export for manual review

For every unresolved `standard` prefix, suggest the closest `international_lab_id` values
(via string similarity) as hints -- not auto-applied, just a head start for whoever reviews
this. Then export **one row per unique prefix/category** -- including the `non_standard_id`
and `unknown_no_lab` buckets -- as the full mapping from every `lab_id` value in the dataset
to a `dating_lab_id`, with a blank `manual_dating_lab_id` column to fill in after review, same
pattern as `landskap_counts.csv`'s export above.

In [48]:
import difflib

all_codes = dating_labs["international_lab_id"].tolist()
unknown_lab_id = dating_labs.loc[dating_labs["international_lab_id"] == "Unknown", "dating_lab_id"].iloc[0]

def suggest_matches(row):
    if row["lab_id_prefix_category"] != "standard" or pd.notna(row["dating_lab_id"]):
        return ""
    close = difflib.get_close_matches(row["lab_id_prefix"], all_codes, n=3, cutoff=0.6)
    return "; ".join(f"{c} (dating_lab_id={exact[c]}, {lab_name_by_id[exact[c]]})" for c in close)

review = prefix_matches.copy()
review["possible_match_suggestions"] = review.apply(suggest_matches, axis=1)

review.loc[review["lab_id_prefix_category"] == "unknown_no_lab",
           ["dating_lab_id", "matched_international_lab_id", "matched_lab_name", "match_type"]] = [
    unknown_lab_id, "Unknown", lab_name_by_id[unknown_lab_id], "unknown_placeholder",
]

review["needs_review"] = (
    review["match_type"].isin(["stripped_star", "unknown_placeholder"]) | review["match_type"].isna()
)
review["manual_dating_lab_id"] = pd.NA

notes = pd.Series("", index=review.index)
notes[review["lab_id_prefix_category"] == "non_standard_id"] = (
    "lab_id doesn't follow <prefix>-<number>; the embedded letter is a sample-type code, not "
    "an international lab code -- needs manual research to identify the lab"
)
notes[review["lab_id_prefix_category"] == "unknown_no_lab"] = (
    "lab_id literally says 'Okänd' with no lab code -- pre-filled with SEAD's generic 'Unknown' "
    "lab; override manual_dating_lab_id if the real lab can be identified"
)
notes[review["match_type"] == "stripped_star"] = (
    "only matches after stripping the DB's trailing '*' and ignoring case -- confirm before trusting it"
)
review["notes"] = notes

review = review[[
    "lab_id_prefix", "lab_id_prefix_category", "n_rows", "example_lab_id", "match_type",
    "dating_lab_id", "matched_international_lab_id", "matched_lab_name",
    "possible_match_suggestions", "needs_review", "manual_dating_lab_id", "notes",
]]

OUTPUT_DIR = Path('../output/lab_id')
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
review.to_csv(OUTPUT_DIR / 'lab_id_prefix_matches.csv', index=False)
review.to_excel(OUTPUT_DIR / 'lab_id_prefix_matches.xlsx', index=False)
print(f"wrote {OUTPUT_DIR}/lab_id_prefix_matches.csv and .xlsx: {len(review)} prefixes covering "
      f"{review['n_rows'].sum()} rows, {review['needs_review'].sum()} flagged for manual review")
review

wrote ..\output\lab_id/lab_id_prefix_matches.csv and .xlsx: 50 prefixes covering 30301 rows, 20 flagged for manual review

,lab_id_prefix,lab_id_prefix_category,n_rows,example_lab_id,match_type,dating_lab_id,matched_international_lab_id,matched_lab_name,possible_match_suggestions,needs_review,manual_dating_lab_id,notes
0,Ua,standard,19691,Ua--15661; Ua-10022; Ua-10023,exact,882.0,Ua,Uppsala Accelerator,,False,<NA>,
1,ST,standard,3622,ST10; ST10006; ST10008,stripped_star,864.0,St*,Stockholm,,True,<NA>,only matches after stripping the DB's trailing...
2,Beta,standard,2954,Beta--48629; Beta-100264; Beta-100265,exact,700.0,Beta,Beta Analytic,,False,<NA>,
3,Poz,standard,749,Poz-10046; Poz-10047; Poz-10048,exact,831.0,Poz,Poznan Radiocarbon Laboratory,,False,<NA>,
4,Lu,standard,492,Lu-100; Lu-1005; Lu-1006,exact,791.0,Lu,Lund,,False,<NA>,
5,"~C (embedded, not a leading prefix)",non_standard_id,488,12C/0126; 14C-5261; 14C-5262,NaN,NaN,NaN,NaN,,True,<NA>,lab_id doesn't follow <prefix>-<number>; the e...
6,GrN,standard,367,GrN-19822; GrN-19823; GrN-19824,exact,743.0,GrN,Groningen,,False,<NA>,
7,LuS,standard,357,LuS-10031; LuS-10069; LuS-10070,case_insensitive,915.0,LUS,Lund University,,False,<NA>,
8,LTL,standard,308,LTL 14001A; LTL-14001A; LTL-14040A,NaN,NaN,NaN,NaN,,True,<NA>,
9,LuA,standard,198,LuA-110; LuA-3750; LuA-3752,NaN,NaN,NaN,NaN,"Lu (dating_lab_id=791, Lund); LAR (dating_lab_...",True,<NA>,
10,T,standard,160,T-10063; T-10111; T-10112,exact,868.0,T,Trondheim,,False,<NA>,
11,U,standard,132,U-1006; U-1010; U-1011,exact,881.0,U,Uppsala,,False,<NA>,
12,KIA,standard,100,KIA-14416; KIA-14417; KIA-14418,exact,778.0,KIA,Kiel AMS,,False,<NA>,
13,KI,standard,97,KI-1300; KI-2287; KI-2289,exact,777.0,KI,Kiel,,False,<NA>,
14,(Okänd -- no lab given at all),unknown_no_lab,85,Okänd 109; Okänd 110; Okänd 111,unknown_placeholder,916.0,Unknown,Unknown or unspecified,,True,<NA>,lab_id literally says 'Okänd' with no lab code...
15,UGAMS,standard,72,UGAMS-10871; UGAMS-10872; UGAMS-10873,NaN,NaN,NaN,NaN,"UGRA (dating_lab_id=891, University of Granada...",True,<NA>,
16,GrA,standard,70,GrA-13503; GrA-13517; GrA-14136,exact,742.0,GrA,Groningen Accelerator,,False,<NA>,
17,UtC,standard,54,UtC-1469; UtC-1470; UtC-1471,exact,896.0,UtC,Utrecht van der Graaf Laboratorium,,False,<NA>,
18,UBA,standard,48,UBA-16601; UBA-20881; UBA-21057,exact,913.0,UBA,Belfast,,False,<NA>,
19,"~P (embedded, not a leading prefix)",non_standard_id,42,15P/0701; 15P/1027; 15P/1202,NaN,NaN,NaN,NaN,,True,<NA>,lab_id doesn't follow <prefix>-<number>; the e...
20,MAMS,standard,28,MAMS-18822; MAMS-18823; MAMS-18824,NaN,NaN,NaN,NaN,"CAMS (dating_lab_id=709, Center for Accelerato...",True,<NA>,
21,AAR,standard,27,"AAR-18430,1; AAR-18430,2; AAR-18431,1",exact,687.0,AAR,University of Aarhus,,False,<NA>,
22,CAIS,standard,26,CAIS-4751; CAIS-4752; CAIS-4753,NaN,NaN,NaN,NaN,"CAMS (dating_lab_id=709, Center for Accelerato...",True,<NA>,
23,"~W (embedded, not a leading prefix)",non_standard_id,20,15W/0651; 16W/0602; 16W/0603,NaN,NaN,NaN,NaN,,True,<NA>,lab_id doesn't follow <prefix>-<number>; the e...
24,MKL,standard,18,MKL-4120; MKL-4121; MKL-4122,NaN,NaN,NaN,NaN,"ML* (dating_lab_id=802, Miami)",True,<NA>,
25,"~B (embedded, not a leading prefix)",non_standard_id,10,16B/1251; 16B/1252; 17B/0142,NaN,NaN,NaN,NaN,,True,<NA>,lab_id doesn't follow <prefix>-<number>; the e...
26,NZA,standard,9,NZA-19401; NZA-I9403; NZA-I9404,exact,818.0,NZA,New Zealand,,False,<NA>,
27,CAMS,standard,8,CAMS-5359; CAMS-5650; CAMS-5651,exact,709.0,CAMS,Center for Accelerator Mass Spectrometry,,False,<NA>,
28,UGA,standard,7,UGA-14067; UGA-14068; UGA-14069,case_insensitive,890.0,UGa,University of Georgia,,False,<NA>,
29,Tln,standard,7,Tln-2408; Tln-2613; Tln-2614,exact,877.0,Tln,Tallinn,,False,<NA>,
30,Lus,standard,6,Lus-13431; Lus-7253; Lus-7254,case_insensitive,915.0,LUS,Lund University,,False,<NA>,
31,WK,standard,6,WK-16542; WK-9081; WK-9082,case_insensitive,903.0,Wk,University of Waikato,,False,<NA>,
32,"~M (embedded, not a leading prefix)",non_standard_id,5,16M/0502; 16M/0503; 16M/0505,NaN,NaN,NaN,NaN,,True,<NA>,lab_id doesn't follow <prefix>-<number>; the e...
33,"~O (embedded, not a leading prefix)",non_standard_id,5,19O/0186; 19O/0187; 19O/0188,NaN,NaN,NaN,NaN,,True,<NA>,lab_id doesn't follow <prefix>-<number>; the e...
34,Lua,standard,5,Lua-4541; Lua-5360; Lua-5363,NaN,NaN,NaN,NaN,"Lu (dating_lab_id=791, Lund)",True,<NA>,
35,"~T (embedded, not a leading prefix)",non_standard_id,4,15T/1001; 15T/1002; 18T/0301,NaN,NaN,NaN,NaN,,True,<NA>,lab_id doesn't follow <prefix>-<number>; the e...
36,Hel,standard,3,Hel-4536; Hel-4541; Hel-4542,exact,752.0,Hel,Helsinki,,False,<NA>,
37,ICA,standard,3,ICA-Okänd 1; ICA-Okänd 2; ICA-Okänd 3,NaN,NaN,NaN,NaN,"KIA (dating_lab_id=778, Kiel AMS); BIOCAMS (da...",True,<NA>,
38,AA,standard,2,AA-1845; AA-1846,exact,686.0,AA,NSF,,False,<NA>,
39,UCLA,standard,2,UCLA-2463F; UCLA-2763B,exact,887.0,UCLA,"University of California, Los Angeles",,False,<NA>,
40,Ki,standard,2,Ki-2477; Ki-3336,case_insensitive,777.0,KI,Kiel,,False,<NA>,
41,KlA,standard,2,KlA-37032; KlA-37033,NaN,NaN,NaN,NaN,"KIA (dating_lab_id=778, Kiel AMS)",True,<NA>,
42,OxA,standard,2,OxA-2789; OxA-2792,exact,824.0,OxA,Oxford Radiocarbon Accelerator Unit,,False,<NA>,
43,"~CB (embedded, not a leading prefix)",non_standard_id,2,16CB/0263,NaN,NaN,NaN,NaN,,True,<NA>,lab_id doesn't follow <prefix>-<number>; the e...
44,ETH,standard,1,ETH-7379,exact,728.0,ETH,ETH/AMS Facility,,False,<NA>,
45,Grn,standard,1,Grn-24657,case_insensitive,743.0,GrN,Groningen,,False,<NA>,
46,Tua,standard,1,Tua-2720,NaN,NaN,NaN,NaN,,True,<NA>,
47,SUERC,standard,1,SUERC-84952,exact,918.0,SUERC,Scottish Universities Environmental Research C...,,False,<NA>,
48,ua,standard,1,ua-26484,case_insensitive,882.0,Ua,Uppsala Accelerator,,False,<NA>,
49,VERA,standard,1,VERA-5148,exact,912.0,VERA,Institut für Radiumforschung und Kernphysik,,False,<NA>,

#### Assigning `dating_lab_id`

Join the per-prefix matches back onto every row. `unknown_no_lab` rows get SEAD's generic
`Unknown` lab by default; everything else stays `NaN` until resolved via the exported CSV
above. `dating_lab_match_type` travels along so low-confidence and unresolved rows stay easy
to filter out downstream if a stricter cut is wanted before ingestion.

In [49]:
df = df.merge(
    prefix_matches[["lab_id_prefix", "lab_id_prefix_category", "dating_lab_id", "match_type"]].rename(
        columns={"match_type": "dating_lab_match_type"}
    ),
    on=["lab_id_prefix", "lab_id_prefix_category"], how="left",
)
df.loc[df["lab_id_prefix_category"] == "unknown_no_lab", ["dating_lab_id", "dating_lab_match_type"]] = [
    unknown_lab_id, "unknown_placeholder",
]
print(f'{df["dating_lab_id"].notna().sum()} / {len(df)} rows have a dating_lab_id')
df[["lab_id", "lab_id_prefix", "lab_id_prefix_category", "dating_lab_id", "dating_lab_match_type"]].sample(10, random_state=1)

29064 / 30301 rows have a dating_lab_id

,lab_id,lab_id_prefix,lab_id_prefix_category,dating_lab_id,dating_lab_match_type
5766,Ua-39061,Ua,standard,882.0,exact
15927,Ua-15810,Ua,standard,882.0,exact
2757,Ua-42292,Ua,standard,882.0,exact
17767,Ua-13733,Ua,standard,882.0,exact
20414,ST4728,ST,standard,864.0,stripped_star
14091,Ua-28887,Ua,standard,882.0,exact
18896,Ua-52373,Ua,standard,882.0,exact
26616,Lu-454,Lu,standard,791.0,exact
16763,Ua-39103,Ua,standard,882.0,exact
10931,Ua-62766,Ua,standard,882.0,exact

## Tasks To Be Done

### Pre-ShapeShifter

- split `site_id` by commas, rename columns to avoid `_id`. **DONE**
- manual map of the unusable values of `landskap`. **DONE**
- split `uppdragsnummer` by commas. **DONE**
- Extract lab prefixes from `lab_id` in a new column. **DONE**
- Standarize lab prefixes according to lab pdf or SEAD's. **DONE for matches against `tbl_dating_labs`; unresolved prefixes still need `lab_id_prefix_matches.csv` filled in by hand**

**To be asked:** 
1. Possible split in the `context_type` for adjectives in a similar feature (see df printed for context_type: "stensättning" appears multiple times with different descriptions like "oval", "rund", "avlång", etc.) 
2. translate `context_type` values (they are in swedish and `tbl_feature_types.feature_type_name` is in english)  

### In ShapeShifter

- Create a column from northing_3006 and easting_3006 with values like f'({str(northing_3006)}, {str(easting_3006)})'
- Create full reference **DONE**
- Create dataset

**To be asked:**

1. How to handle `lab_id` being almos unique to every row. Should we create a dataset for every one of those?
2. How to create the dataset, sample groups, physical samples, analysis entities, etc.
  -> from my understanding, as analysis_entity would require dataset_id and physical_sample_id, we would need first to create those entities, and for physical_sample one needs a sample_group_id defined, so there is some entities that require their parents to be created first, therefore one needs to define those first. Sample group names and dataset names to be defined